Repository mitre/caldera, pull requests merged in 2020-04, with the labels that each got.

#1502 fix: change default values for Ability() (cosmetic + avoid NoneType error)
  app/objects/c_ability.py
Labels: bug, enhancement

#1538 Also search within names and descriptions
  static/js/ability.js
Labels: enhancement

#1596 Patch adversary UI rendering
  app/service/rest_svc.py
Labels: bug
